FROM alpine:3.11.3
MAINTAINER MingyiJin
COPY requirement.txt /root/requirement.txt
COPY Server /root/JudgerServer
COPY Judger /root/Judger
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories \
    && apk update && apk add --no-cache \
    bash gcc g++ make cmake sudo supervisor linux-headers \
    python python3 python3-dev openjdk8 go libseccomp-dev && rm -rf /var/cache/apk/* \
    && pip3 install --no-cache-dir -r /root/requirement.txt -i https://mirrors.aliyun.com/pypi/simple/ \
    && cd /root/Judger && mkdir build && cd build && cmake .. && make && make install \
    && cd ../bindings/Python && python3 setup.py install && rm -rf /root/Judger && mkdir /var/log/supervisor
COPY supervisord.conf /etc/supervisord.conf
ENV TZ=Asia/Shanghai \
    LANG=en_US.UTF-8 \
    LANGUAGE=en_US:en \
    OJ_BACKEND_CALLBACK=http://localhost:8080/callback
CMD supervisord